/** Локальная палитра чата: Unicode-смайлики и понятные русские подписи. */
export const CHAT_EMOJIS = [
  { emoji: "😀", label: "Улыбка" },
  { emoji: "😃", label: "Радость" },
  { emoji: "😄", label: "Счастливая улыбка" },
  { emoji: "😁", label: "Широкая улыбка" },
  { emoji: "😆", label: "Смех" },
  { emoji: "😅", label: "Улыбка с каплей пота" },
  { emoji: "😂", label: "Слёзы радости" },
  { emoji: "🤣", label: "Катаюсь от смеха" },
  { emoji: "😊", label: "Смущённая улыбка" },
  { emoji: "🙂", label: "Лёгкая улыбка" },
  { emoji: "🙃", label: "Перевёрнутая улыбка" },
  { emoji: "😉", label: "Подмигивание" },
  { emoji: "😍", label: "Влюблённый взгляд" },
  { emoji: "🥰", label: "Улыбка с сердечками" },
  { emoji: "😘", label: "Воздушный поцелуй" },
  { emoji: "😋", label: "Вкусно" },
  { emoji: "😛", label: "Показываю язык" },
  { emoji: "😜", label: "Подмигиваю с языком" },
  { emoji: "🤪", label: "Дурачусь" },
  { emoji: "😎", label: "В солнечных очках" },
  { emoji: "🤓", label: "Умник" },
  { emoji: "🧐", label: "Разглядываю" },
  { emoji: "🤩", label: "Восторг" },
  { emoji: "🥳", label: "Праздную" },
  { emoji: "😏", label: "Усмешка" },
  { emoji: "😌", label: "Облегчение" },
  { emoji: "🤔", label: "Думаю" },
  { emoji: "🤨", label: "Сомневаюсь" },
  { emoji: "😐", label: "Без эмоций" },
  { emoji: "😶", label: "Без слов" },
  { emoji: "🙄", label: "Закатываю глаза" },
  { emoji: "😬", label: "Неловко" },
  { emoji: "😮", label: "Удивление" },
  { emoji: "😲", label: "Сильное удивление" },
  { emoji: "😴", label: "Сплю" },
  { emoji: "🥱", label: "Зеваю" },
  { emoji: "😢", label: "Грусть" },
  { emoji: "😭", label: "Плачу" },
  { emoji: "😤", label: "Возмущение" },
  { emoji: "😡", label: "Злость" },
  { emoji: "🥺", label: "Прошу" },
  { emoji: "😱", label: "Испуг" },
  { emoji: "🤯", label: "Взрыв мозга" },
  { emoji: "🤗", label: "Обнимаю" },
  { emoji: "🤭", label: "Прикрываю рот" },
  { emoji: "🤫", label: "Тихо" },
  { emoji: "🤝", label: "Рукопожатие" },
  { emoji: "👍", label: "Палец вверх" },
  { emoji: "👎", label: "Палец вниз" },
  { emoji: "👏", label: "Аплодисменты" },
  { emoji: "🙌", label: "Ура" },
  { emoji: "🙏", label: "Спасибо" },
  { emoji: "👋", label: "Привет" },
  { emoji: "👌", label: "Отлично" },
  { emoji: "✌️", label: "Победа" },
  { emoji: "💪", label: "Сила" },
  { emoji: "❤️", label: "Красное сердце" },
  { emoji: "💙", label: "Синее сердце" },
  { emoji: "💚", label: "Зелёное сердце" },
  { emoji: "💜", label: "Фиолетовое сердце" },
  { emoji: "🔥", label: "Огонь" },
  { emoji: "🎉", label: "Праздничная хлопушка" },
  { emoji: "✨", label: "Искры" },
  { emoji: "😺", label: "Улыбающийся кот" },
] as const;
